services:
  app:
    image: johnkristan/ai-jarvis-designs:latest
    container_name: ai_jarvis_designs_server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge