name: Build AI Jarvis Designs Docker Image
on:
    push:
      branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

        - name: Build Docker Image
          run: docker build -t johnkristan/ai-jarvis-designs:latest .

        - name: Push Docker Image to Docker Hub
          run: docker push johnkristan/ai-jarvis-designs:latest

    trigger-deploy:
        name: Trigger Deployment
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Trigger deploy workflow
          uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                await github.rest.actions.createWorkflowDispatch({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    workflow_id: 'deploy.yml',
                    ref: 'main',
                });
                console.log('✅ Deploy workflow triggered');